name: FolkTool
description: "FolkTool - KernelPatch 自动刷入工具"
publish_to: 'none'
version: 1.2.1+3

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.0
  process_run: ^1.2.0
  file_picker: ^8.0.0
  path_provider: ^2.1.0
  path: ^1.8.0
  shared_preferences: ^2.2.0
  uuid: ^4.0.0
  intl: ^0.20.2
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  intl_utils: ^2.8.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/kpimg
    - bin/
    - kptools/
    - apk/

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false
  output_localization_file: l10n.dart
  main_class: AppLocalizations
